const base = {size:'M',sizes:['XS','S','M','L','XL'],condition:'Excellent',rating:4.8,location:'Chennai',brand:'AR Studio',style:'Modern',color:'Black',gender:'Women',seller:'Ananya R.',verified:true,deposit:1000,duration:3,booked:[],kind:'Pre-owned',notes:['No stains','No tears'],occasions:['Party','Date'],mode:['Rent','Buy','Swap']};
export const products = [
  {id:'p1',name:'The Gulabi Bridal Lehenga',category:'Lehengas',image:'lehenga',price:4999,original:45000,deposit:5000,color:'Rose',style:'Traditional',brand:'AR Studio',occasions:['Bridal','Wedding','Engagement','Festival','Traditional'],kind:'Designer',featured:true},
  {id:'p2',name:'Midnight Satin Slip Dress',category:'Dresses',image:'dress',price:899,original:6999,color:'Black',brand:'Mira Atelier',occasions:['Party','Reception','Date','Photoshoot'],featured:true},
  {id:'p3',name:'The Heirloom Silk Saree',category:'Sarees',image:'saree',price:1499,original:18000,color:'Gold',style:'Traditional',brand:'Thread & Tale',occasions:['Wedding','Festival','Traditional','Engagement'],featured:true},
  {id:'p4',name:'The Everyday Tailored Blazer',category:'Suits',image:'suit',price:599,original:4999,gender:'Men',brand:'Northline',occasions:['Office','College','Interview'],featured:true},
  {id:'p5',name:'Classic Black Leather Jacket',category:'Jackets',image:'jacket',price:399,original:3999,sale:1800,brand:'Northline',style:'Streetwear',gender:'Unisex',occasions:['College','Casual','Vacation'],mode:['Swap','Buy','Rent']},
  {id:'p6',name:'Vintage Straight-leg Denim',category:'Jeans',image:'jeans',price:249,original:2599,sale:1200,brand:'Northline',color:'Blue',style:'Vintage',gender:'Unisex',occasions:['College','Casual','Vacation'],kind:'Vintage'},
  {id:'p7',name:'Ivory Linen Shirt',category:'Shirts',image:'shirt',price:299,original:2999,sale:1400,brand:'Thread & Tale',color:'Ivory',style:'Minimal',gender:'Men',occasions:['Office','Casual','Vacation']},
  {id:'p8',name:'The City Edit Co-ord',category:'Streetwear',image:'street',price:699,original:5999,brand:'Mira Atelier',style:'Streetwear',occasions:['College','Casual','Photoshoot']},
  {id:'p9',name:'Heritage Wedding Sherwani',category:'Sherwanis',image:'suit',price:1999,original:22000,deposit:3000,brand:'AR Studio',gender:'Men',style:'Traditional',color:'Ivory',occasions:['Wedding','Engagement','Traditional'],kind:'Designer'},
  {id:'p10',name:'Gold-plated Heritage Necklace',category:'Accessories',image:'jewel',price:299,original:4999,brand:'Thread & Tale',color:'Gold',style:'Traditional',occasions:['Wedding','Bridal','Festival']},
  {id:'p11',name:'The Little Occasion Clutch',category:'Accessories',image:'bag',price:199,original:2499,brand:'Mira Atelier',occasions:['Wedding','Bridal','Party','Reception']},
  {id:'p12',name:'Little Celebrations Dress',category:'Dresses',image:'dress',price:499,original:2999,gender:'Kids',sizes:['4Y','6Y','8Y','10Y'],size:'6Y',occasions:['Party','Wedding'],kind:'New'},
  {id:'p13',name:'Handwoven Festive Lehenga',category:'Lehengas',image:'lehenga',price:2499,original:18000,deposit:2500,brand:'Thread & Tale',style:'Traditional',color:'Rose',kind:'Handmade',occasions:['Wedding','Bridal','Festival','Traditional']},
  {id:'p14',name:'The Weekend Cotton Tee',category:'T-shirts',image:'shirt',price:149,original:1299,sale:500,brand:'Northline',gender:'Unisex',color:'Ivory',style:'Streetwear',occasions:['College','Casual','Vacation'],kind:'New'},
  {id:'p15',name:'Ivory Indo-Western Celebration Set',category:'Indo-Western',image:'suit',price:1799,original:18000,brand:'AR Studio',gender:'Men',color:'Ivory',style:'Traditional',occasions:['Wedding','Reception','Festival'],kind:'Designer'},
  {id:'p16',name:'Rose Bridesmaid Occasion Dress',category:'Bridesmaid Dress',image:'dress',price:999,original:8000,brand:'Mira Atelier',color:'Rose',occasions:['Wedding','Reception','Engagement'],kind:'Designer'},
  {id:'p17',name:'Reception Evening Gown',category:'Reception Dress',image:'dress',price:1599,original:16000,brand:'Mira Atelier',occasions:['Reception','Party','Photoshoot'],kind:'Designer'},
  {id:'p18',name:'The Engagement Celebration Outfit',category:'Engagement Outfit',image:'saree',price:1299,original:14000,brand:'Thread & Tale',color:'Gold',style:'Traditional',occasions:['Engagement','Wedding','Traditional'],kind:'Handmade'},
  {id:'p19',name:'Handmade Festive Jewellery Set',category:'Jewellery',image:'jewel',price:399,original:5999,brand:'Thread & Tale',color:'Gold',style:'Traditional',occasions:['Bridal','Wedding','Festival'],kind:'Handmade'}
].map((p,i)=>({...base,...p,sale:p.sale||Math.round(p.original*.55),booked:i===0?['2026-10-12','2026-10-13']:[],reviews:[{name:'Riya K.',text:'Beautiful finish and a lovely fit. Ananya was so helpful.',rating:5},{name:'Diya S.',text:'Just right for my occasion. Would wear it again.',rating:4}]}));
export const designers=[
  {id:'ar',name:'AR Studio',initials:'AR',tag:'Crafted with a story',image:'saree',city:'Chennai',type:'Independent',followers:1240,rating:4.9,description:'Contemporary Indian fashion inspired by traditional craftsmanship. Small collections, thoughtful details, and pieces made to be worn again.',brand:'AR Studio'},
  {id:'mira',name:'Mira Atelier',initials:'MA',tag:'A softer kind of statement',image:'dress',city:'Mumbai',type:'Student',followers:860,rating:4.8,description:'A fashion student exploring fluid silhouettes and modern occasionwear. Designed for your everyday main-character moments.',brand:'Mira Atelier'},
  {id:'thread',name:'Thread & Tale',initials:'TT',tag:'Tradition, reimagined',image:'lehenga',city:'Jaipur',type:'Small label',followers:980,rating:4.9,description:'Handcrafted textiles meet modern silhouettes. A small independent label celebrating the artisans behind every piece.',brand:'Thread & Tale'},
  {id:'north',name:'Northline',initials:'N',tag:'Less, but better',image:'jacket',city:'Bengaluru',type:'Freelance',followers:610,rating:4.7,description:'Considered essentials and expressive streetwear. A freelance designer creating a wardrobe beyond the season.',brand:'Northline'}
];
export const occasions=['Bridal','Wedding','Reception','Engagement','Party','College','Office','Casual','Festival','Vacation','Photoshoot','Traditional'];
export const categories=['Tops','Shirts','T-shirts','Pants','Jeans','Dresses','Sarees','Lehengas','Sherwanis','Suits','Jackets','Streetwear','Shoes','Accessories'];
export const initialWardrobe=[{id:'w1',name:'My black jacket',category:'Jackets',image:'assets/jacket.jpg',size:'M',brand:'Northline',style:'Streetwear',color:'Black',value:1700,gender:'Unisex',location:'Chennai',condition:'Excellent'},{id:'w2',name:'My favourite jeans',category:'Jeans',image:'assets/jeans.jpg',size:'M',brand:'Northline',style:'Vintage',color:'Blue',value:1200,gender:'Unisex',location:'Chennai',condition:'Excellent'},{id:'w3',name:'The white shirt',category:'Shirts',image:'assets/shirt.jpg',size:'M',brand:'Thread & Tale',style:'Minimal',color:'Ivory',value:1400,gender:'Unisex',location:'Chennai',condition:'Like New'}];
