/* GadgetPulse application: ordinary DOM events, hash routes and browser storage. */
(function () {
  'use strict';
  const D=window.GadgetPulseData,C=window.GadgetPulseCore,V=window.GadgetPulseViews;
  const e=C.escapeHTML,m=C.money,$=selector=>document.querySelector(selector);
  const storageKey='gadgetpulse-html-v1';
  let state,storageAvailable=true,modal=null,toastTimer,mediaURLs=[],profileGeneration=0;
  try {state=C.normalizeState(JSON.parse(localStorage.getItem(storageKey)||'null'),D.products.map(p=>p.id));}catch(_){state=C.normalizeState(null,D.products.map(p=>p.id));}
  function products() {return D.products.map(p=>{const o=state.overrides[p.id];return {...p,price:o?.price||p.price,history:o?.price?[...p.history.slice(0,-1),o.price]:p.history,priceRecord:{...p.priceRecord,price:o?.price||p.price}};});}
  function newsItems() {return D.news.map(n=>({...n,...state.newsOverrides[n.id]}));}
  function toast(message) {$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3800);}
  function save() {
    try {localStorage.setItem(storageKey,JSON.stringify(state));storageAvailable=true;return true;}
    catch(_){storageAvailable=false;toast('Browser storage is unavailable or full. Changes will last only while this page stays open.');return false;}
  }
  function notifySaved(message) {if(save())toast(message);}
  function route() {const [path,query='']=(location.hash.slice(1)||'home').split('?');return {path,params:new URLSearchParams(query)};}
  function goto(path,params={}) {closeDialog();const query=new URLSearchParams(params).toString();const hash=`#${path}${query?'?'+query:''}`;if(location.hash===hash)render();else location.hash=hash;}
  function updateChrome() {
    $('#wish-count').textContent=state.wishlist.length||'';
    $('#alert-count').textContent=state.alerts.length||'';
    $('#mobile-compare-count').textContent=state.comparisons.length||'';
    const {path}=route();document.querySelectorAll('.desktop-nav a,.mobile-nav a').forEach(a=>{a.classList.toggle('active',a.hash==='#'+path);if(a.hash==='#'+path)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
    const tray=$('#compare-tray');tray.hidden=!state.comparisons.length||path==='compare';
    tray.innerHTML=`<span><b>${state.comparisons.length}/4</b> selected</span><div>${state.comparisons.map(id=>{const p=products().find(x=>x.id===id);return `<button data-action="compare" data-id="${id}" aria-label="Remove ${e(p.name)} from comparison">${e(p.name)} ×</button>`;}).join('')}</div><a class="button primary small" href="#compare">Compare now ⇄</a><button class="icon-button" data-action="clear-compare" aria-label="Clear comparisons">×</button>`;
  }
  function listPage(all,path,params) {
    const q=params.get('q')||'',category=D.CATEGORIES.includes(params.get('category'))?params.get('category'):'All';
    const requested=Number(params.get('budget')),budget=C.validTarget(requested)?requested:Infinity;
    const brand=params.get('brand')||'All',sort=params.get('sort')||'recommended';
    let selected=C.filterProducts(all,q,category,budget);
    if(brand!=='All')selected=selected.filter(p=>p.brand===brand);
    if(path==='trending')selected=selected.filter(p=>p.status==='Trending'||state.overrides[p.id]?.featured);
    if(path==='latest')selected.sort((a,b)=>b.launch.localeCompare(a.launch));
    if(path==='deals')selected.sort((a,b)=>(1-b.price/b.mrp)-(1-a.price/a.mrp));
    if(sort==='price-low')selected.sort((a,b)=>a.price-b.price);
    if(sort==='price-high')selected.sort((a,b)=>b.price-a.price);
    if(sort==='score')selected.sort((a,b)=>b.score-a.score);
    const titles={explore:'Find your next upgrade.',latest:'Fresh arrivals. New possibilities.',deals:'Great gadgets. Better sample prices.',trending:'The conversation starters.'};
    return V.heading(titles[path],path==='deals'?'Discounts from the demo catalog. No live sale or seller feed is connected.':'Explore 28 demo devices. Search by name, budget or what matters to you.',path==='explore'?'EXPLORE DEVICES':path.toUpperCase())+V.searchForm(q)+`<form class="filter-bar" id="filter-form"><div class="field"><label for="filter-category">Category</label><select name="category" id="filter-category"><option>All</option>${D.CATEGORIES.map(cat=>`<option ${category===cat?'selected':''}>${cat}</option>`).join('')}</select></div><div class="field"><label for="filter-brand">Brand</label><select name="brand" id="filter-brand"><option>All</option>${[...new Set(all.map(p=>p.brand))].sort().map(b=>`<option ${brand===b?'selected':''}>${e(b)}</option>`).join('')}</select></div><div class="field"><label for="filter-budget">Maximum price (₹)</label><input id="filter-budget" name="budget" type="number" min="1" max="10000000" placeholder="Any budget" value="${budget===Infinity?'':budget}"></div><div class="field"><label for="filter-sort">Sort by</label><select name="sort" id="filter-sort">${[['recommended','Recommended'],['price-low','Price: low to high'],['price-high','Price: high to low'],['score','Pulse score']].map(([value,label])=>`<option value="${value}" ${sort===value?'selected':''}>${label}</option>`).join('')}</select></div><button class="button secondary">Apply filters</button><a href="#${path}" class="text-link">Reset</a></form><div class="results-line"><p><b>${selected.length}</b> ${selected.length===1?'device':'devices'} ${q?'matching “'+e(q)+'”':''}</p>${q?`<button class="text-link" data-action="save-search" data-query="${e(q)}">♡ Save this search</button>`:'<span class="demo-label">Demo Data · Snapshot 6 Oct 2026</span>'}</div>${V.grid(selected,state)}${path==='latest'?`<div class="section">${V.section('Coming soon.','Rumored / Expected · Fictional preview examples.')}<div class="upcoming-grid">${D.upcoming.map(p=>`<article class="upcoming-card">${V.art(p.art,p.color)}<div><span class="pill">${e(p.status)} · Demo</span><h3>${e(p.name)}</h3><p>${e(p.features)}</p><p>${e(p.date)} · ${e(p.price)}</p></div></article>`).join('')}</div></div>`:''}`;
  }
  function profile(all) {
    const p=state.preferences;
    return V.heading(`Hello, ${state.name}.`,'Your next favorite gadget starts here. Everything on this profile stays in this browser.','YOUR SPACE')+`<div class="profile-stats">${[['Wishlist',state.wishlist.length,'wishlist'],['Comparisons',state.comparisons.length,'compare'],['Price targets',state.alerts.length,'alerts'],['Your reviews',state.reviews.length,'profile']].map(([label,count,path])=>`<a href="#${path}" class="panel"><strong>${count}</strong><span>${label} ↗</span></a>`).join('')}</div><div class="profile-columns"><div class="panel"><h3>Your taste in tech.</h3><p>Budget: <b>${m(p.budget)}</b> · Priority: <b>${e(p.priority)}</b></p><p>Categories: ${p.categories.length?p.categories.map(e).join(', '):'All categories'}</p><p>Brands: ${p.brands.length?p.brands.map(e).join(', '):'All brands'}</p><p>Use cases: ${p.useCases.length?p.useCases.map(e).join(', '):'Not selected'}</p><p>In-app notifications: ${p.notifications?'On':'Off'}</p><a class="button secondary" href="#preferences">Edit preferences ↗</a></div><div class="panel"><h3>Pick up where you left off.</h3><h4>Saved searches</h4>${state.searches.length?state.searches.map(q=>`<div class="saved-row"><button class="text-link" data-action="quick-search" data-query="${e(q)}">${e(q)} ↗</button><button class="icon-button" data-action="delete-search" data-query="${e(q)}" aria-label="Remove saved search ${e(q)}">×</button></div>`).join(''):'<p class="muted">Save a search from the device results page.</p>'}<button class="button small secondary" data-action="export">Download my saved data ↓</button><button class="button small secondary" data-action="reset">Reset this profile</button><p class="demo-label">No account, cloud synchronization, email or ChatGPT connection. ${storageAvailable?'Browser storage active.':'Browser storage unavailable.'}</p></div></div><section class="section">${V.section('Recently viewed.','A second look can make all the difference.')} ${V.grid(state.recent.map(id=>all.find(p=>p.id===id)).filter(Boolean).slice(0,8),state)}</section><section class="section">${V.section('Your reviews.','Local reviews, saved only on this browser.')}${state.reviews.length?state.reviews.map(r=>`<article class="panel review"><div class="product-meta"><button class="text-link" data-action="detail-reviews" data-id="${r.productId}">${e(all.find(p=>p.id===r.productId)?.name)} ↗</button><span class="rating">${'★'.repeat(r.rating)}</span></div><p class="review-text">${e(r.text)}</p><p class="demo-label">${e(r.date)} · Purchase unverified</p>${V.btn('Delete review','delete-review',r.id,'button secondary small')}</article>`).join(''):V.empty('Your experience matters.','Open a device and choose Your reviews to share it.','explore','Explore gadgets')}</section>`;
  }
  function alerts(all) {
    const reached=state.alerts.filter(a=>all.find(p=>p.id===a.productId)?.price<=a.target);
    return V.heading('Keep an eye on your next upgrade.','Targets are checked against the demo catalog while you use this page. No background monitoring or push/email delivery runs.','PRICE ALERTS')+`<div class="notice">${state.preferences.notifications?`${reached.length} sample price ${reached.length===1?'target':'targets'} reached.`:'In-app notifications are off. Enable them in Preferences.'} Notification settings and all target types are local demo preferences.</div>${state.alerts.length?`<div class="alert-grid">${state.alerts.map(a=>{const p=all.find(x=>x.id===a.productId),hit=p.price<=a.target;return `<article class="panel alert-card">${V.art(p.art,p.color)}<div><span class="pill ${hit?'green-pill':''}">${hit?'Demo target reached':'Watching sample price'}</span><h3>${e(p.name)}</h3><p>Target <b>${m(a.target)}</b> · Current demo <b>${m(p.price)}</b></p><p class="muted">${a.types.map(e).join(' · ')||'Price drop'}</p><div class="chips">${V.btn('Edit target','track',p.id,'button small secondary')}${V.btn('View device','detail',p.id,'button small secondary')}${V.btn('Remove','remove-alert',p.id,'button small secondary')}</div></div></article>`;}).join('')}</div>`:V.empty('Good things are worth watching.','Use Track price on any gadget to save a target.','explore','Find a gadget to track')}<div class="panel section"><h3>Your local demo feed.</h3><p class="muted">${state.preferences.notifications?'Sample launches and deals based on your followed categories and brands. These are not live notifications.':'Notifications are off.'}</p>${state.preferences.notifications?all.filter(p=>(!state.preferences.brands.length||state.preferences.brands.includes(p.brand))&&(!state.preferences.categories.length||state.preferences.categories.includes(p.category))).slice(0,4).map(p=>`<div class="saved-row"><span>${e(p.status)} · ${e(p.name)} · Demo ${m(p.price)}</span>${V.btn('View ↗','detail',p.id,'button small secondary')}</div>`).join(''):''}</div>`;
  }
  function admin(all,params) {
    const tabs=['Products','Brands','News','Reviews','Price data','Local availability','Deals','Users','Reports','Trending','Featured'];
    const tab=tabs.includes(params.get('tab'))?params.get('tab'):'Products';
    let body='';
    if(['Products','Price data','Deals','Trending','Featured'].includes(tab))body=`<div class="manager-grid">${all.map(p=>`<form class="panel admin-form" data-id="${p.id}"><span class="eyebrow">${e(p.brand)} · ${e(p.category)}</span><h3>${e(p.name)}</h3><div class="field"><label for="admin-price-${p.id}">Demo price (₹)</label><input id="admin-price-${p.id}" name="price" type="number" min="1" max="10000000" step="1" value="${p.price}" required></div><label class="checkbox-line"><input type="checkbox" name="featured" ${state.overrides[p.id]?.featured?'checked':''}> Feature on home / trending</label><label class="checkbox-line"><input type="checkbox" name="reviewed" ${state.overrides[p.id]?.reviewed?'checked':''}> Demo source reviewed locally</label><p class="demo-label">Source: GadgetPulse sample catalog. A local review mark does not verify real pricing or manufacturer data.</p><button class="button secondary small">Save local changes</button></form>`).join('')}</div>`;
    if(tab==='News')body=`<div class="manager-grid">${newsItems().map(n=>`<form class="panel news-admin-form" data-id="${n.id}"><div class="field"><label for="title-${n.id}">Editorial title</label><input id="title-${n.id}" name="title" value="${e(n.title)}" maxlength="200" required></div><div class="field"><label for="summary-${n.id}">Summary</label><textarea id="summary-${n.id}" name="summary" maxlength="1000" required>${e(n.summary)}</textarea></div><p class="demo-label">Only the title and summary change; the article remains a demo.</p><button class="button secondary">Save demo article</button></form>`).join('')}</div>`;
    if(tab==='Brands')body=`<div class="brand-grid">${Object.entries(D.officialStores).map(([brand,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer" class="panel"><b>${e(brand)} ↗</b><p class="muted">Manufacturer website</p></a>`).join('')}</div>`;
    if(tab==='Reviews')body=state.reviews.length?state.reviews.map(r=>`<article class="panel review"><h3>${e(all.find(p=>p.id===r.productId)?.name)}</h3><p>${e(r.text)}</p><span class="demo-label">Local review · Purchase unverified</span>${V.btn('Delete review','delete-review',r.id)}</article>`).join(''):V.empty('No local reviews.','Reviews written in this browser appear here.','','');
    if(tab==='Local availability')body=`<div class="panel"><h3>Sample inventory coverage</h3><p>Five cities: ${Object.keys(D.cities).join(', ')}. Store inventory, distance and ratings are fictional.</p><a class="button secondary" href="#nearby">Open sample nearby offers ↗</a></div>`;
    if(tab==='Users')body=`<div class="panel"><h3>One local browser profile</h3><p>${e(state.name)} · No accounts or authentication.</p><p>Public users and role-based admin permissions require a backend. This manager edits only this browser’s demo catalog.</p></div>`;
    if(tab==='Reports')body=`<div class="profile-stats">${[['Demo products',all.length],['Local reviews',state.reviews.length],['Saved targets',state.alerts.length],['Featured products',Object.values(state.overrides).filter(v=>v.featured).length]].map(([label,value])=>`<div class="panel"><strong>${value}</strong><span>${label}</span></div>`).join('')}</div><div class="panel"><h3>Data provenance</h3><p>All prices, scores, history, releases and stock come from the demo catalog. No catalog, retailer, news, review or inventory APIs are connected.</p></div>`;
    return V.heading('Your local demo studio.','Edit sample content in this browser. This is a demo manager, with no admin authentication or public-user privileges.','CATALOG MANAGER')+`<div class="chips manager-tabs">${tabs.map(t=>`<a class="chip ${t===tab?'active':''}" href="#admin?tab=${encodeURIComponent(t)}">${t}</a>`).join('')}</div>${body}`;
  }
  function about() {return V.heading('Clarity over hype. Always.','Know it. Compare it. Buy it.','ABOUT GADGETPULSE')+`<div class="about-grid"><article class="panel"><h2>Three languages. One smarter experience.</h2><p>This website uses HTML for structure, CSS for the visual design and plain JavaScript for the interactions. It has no framework, package installation, build step, account or ChatGPT connection.</p><p>Open index.html directly to use it. Browser-local saved data may behave differently across browsers when opened as a file. Hosting these same static files gives them a stable website address.</p></article><article class="panel"><h2>Understand your data.</h2><p>Product names refer to familiar brands; their specifications, prices, ratings, release dates, stock, popularity, price history and local-store information are illustrative <b>Demo Data</b>.</p><p>News articles are original demo editorial content. Upcoming devices are fictional examples labeled Rumored / Expected. Manufacturer links open real brand websites; the demo prices are not offers from those websites.</p><p>The sample catalog snapshot is 6 Oct 2026. Nearby offer records include INR currency, fictional seller, city, timestamp and source. None is real-time.</p></article><article class="panel"><h2>Saved right here.</h2><p>Wishlist, comparisons, preferences, searches, review text and price targets use localStorage. Optional review photos and videos use IndexedDB. They stay in this browser; clearing its storage removes them.</p><p>No background price monitoring, email, push notifications, public review sharing, verified purchases or protected admin accounts are implemented. The local demo manager is for editing your sample experience.</p></article><article class="panel"><h2>A thoughtful decision, explained.</h2><p>Search recognizes device names, budget phrases such as “under 30k” and “under 1 lakh”, and priorities such as gaming, camera and coding. Recommendations rank the sample catalog using your priorities and use cases. They do not call an AI service.</p><p>Pulse score is the average of nine demo scores. Value score uses 75% of that score plus a bounded affordability component. Wait or Buy checks whether the sample price is within 5% of the sample historical low. Neither predicts or guarantees future prices.</p><p>Live browser-accessible APIs can be added to the catalog provider later. Private API keys need a secure backend and should never go into these JavaScript files.</p></article></div>`;}
  function render() {
    const {path,params}=route(),all=products();let body='';
    if(path==='home')body=V.home(all,state,newsItems());
    else if(['explore','latest','deals','trending'].includes(path))body=listPage(all,path,params);
    else if(path==='compare')body=V.compare(all,state);
    else if(path==='finder')body=V.finder(all,state,params);
    else if(path==='nearby')body=V.nearby(all,state,params);
    else if(path==='preferences'||path==='onboarding')body=V.preferences(state,path==='onboarding');
    else if(path==='wishlist')body=V.heading('Your next favorites.','Good discoveries deserve a place to stay.','WISHLIST')+(state.wishlist.length?V.grid(all.filter(p=>state.wishlist.includes(p.id)),state):V.empty('Your next favorite gadget belongs here.','Tap the heart on any gadget to keep it close.','explore','Explore gadgets'));
    else if(path==='profile')body=profile(all);
    else if(path==='alerts')body=alerts(all);
    else if(path==='admin')body=admin(all,params);
    else if(path==='about')body=about();
    else if(path==='news'){
      const query=params.get('q')||'',followed=params.get('followed')==='1',topic=params.get('topic')||'All';
      const selected=newsItems().filter(n=>(!followed||!state.preferences.brands.length||state.preferences.brands.includes(n.brand))&&(topic==='All'||n.category===topic)&&`${n.title} ${n.summary} ${n.brand}`.toLowerCase().includes(query.toLowerCase()));
      body=V.heading('Stay curious. Stay ahead.','An original demo editorial feed. No live news API is connected.','LATEST TECH')+`<form id="news-filter" class="filter-bar"><div class="field"><label for="news-search">Search articles</label><input id="news-search" name="q" value="${e(query)}" placeholder="AI, display, audio…"></div><div class="field"><label for="news-topic">Topic</label><select id="news-topic" name="topic"><option>All</option>${D.news.map(n=>n.category).map(t=>`<option ${t===topic?'selected':''}>${e(t)}</option>`).join('')}</select></div><label class="checkbox-line"><input type="checkbox" name="followed" ${followed?'checked':''}> My followed brands</label><button class="button secondary">Apply</button></form><div class="news-grid">${selected.map(V.newsCard).join('')}</div>${!selected.length?V.empty('Nothing in this feed yet.','Change the topic or followed-brand filter.','news','Show all articles'):''}<div class="panel section"><h3>Upcoming technology</h3><div class="chips">${['AI chips','Foldable phones','Display technology','Battery technology','Fast charging','AI laptops','AR / VR','Gaming hardware','Smart home'].map(t=>`<span class="chip">${t}</span>`).join('')}</div><p class="muted">Topics to watch — examples, not reports of confirmed announcements.</p><a class="text-link" href="#preferences">Customize followed brands ↗</a></div>`;
    } else body=V.empty('This page is off the map.','Let’s get back to discovering.','home','Back home');
    $('#content').className=path==='home'?'':'container page-content';$('#content').innerHTML=body;
    document.title=`${path==='home'?'Discover what’s next':path.charAt(0).toUpperCase()+path.slice(1)} — GadgetPulse`;
    if(!state.onboarded&&path==='home')$('#content').insertAdjacentHTML('beforeend','<div class="container welcome-note"><div><b>A little more you.</b><span> Choose your interests for a personalized feed.</span></div><a class="button small secondary" href="#onboarding">Get started ↗</a><button class="icon-button" data-action="dismiss-onboarding" aria-label="Dismiss welcome tip">×</button></div>');
    updateChrome();
  }
  function releaseMedia() {mediaURLs.forEach(URL.revokeObjectURL);mediaURLs=[];}
  function closeDialog() {if($('#detail-dialog').open)$('#detail-dialog').close();modal=null;releaseMedia();}
  function showDialog(html) {releaseMedia();$('#detail-body').innerHTML=html;if(!$('#detail-dialog').open)$('#detail-dialog').showModal();$('#detail-dialog').scrollTop=0;}
  function openProduct(id,tab='specs',record=true) {
    const p=products().find(x=>x.id===id);if(!p)return;
    if(record){state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,20);save();}
    modal={type:'product',id,tab};showDialog(V.detail(p,products(),state,tab));if(tab==='reviews')hydrateMedia();
  }
  async function hydrateMedia() {
    const nodes=Array.from(document.querySelectorAll('[data-media-key]'));
    for(const node of nodes){try{const file=await window.GadgetPulseMedia.get(node.dataset.mediaKey);if(!node.isConnected)continue;if(!file){node.textContent='Attachment unavailable on this browser.';continue;}const url=URL.createObjectURL(file);mediaURLs.push(url);const child=document.createElement(file.type.startsWith('video/')?'video':'img');child.src=url;if(child.tagName==='VIDEO'){child.controls=true;child.preload='metadata';}else{child.alt='Photo attached to a local user review';child.loading='lazy';}node.replaceChildren(child);}catch(_){if(node.isConnected)node.textContent='Browser attachment storage unavailable.';}}
  }
  function refresh() {const current=modal;render();if(current?.type==='product')openProduct(current.id,current.tab,false);}
  function track(id) {
    const p=products().find(x=>x.id===id);if(!p)return;const target=state.alerts.find(a=>a.productId===id),types=target?.types||['Price drop'];
    modal={type:'track',id};showDialog(`<div class="track-dialog"><span class="eyebrow">A LITTLE PATIENCE. A BETTER PRICE.</span><h1 id="detail-title">Track ${e(p.name)}</h1><p>Current sample price: <b>${m(p.price)}</b></p><form id="track-form" data-id="${id}"><div class="field"><label for="target-price">Notify me at this price (₹)</label><input id="target-price" name="target" type="number" min="1" max="10000000" step="1" value="${target?.target||Math.round(p.price*.9)}" required></div><fieldset><legend>What do you want to watch?</legend>${['Price drop','Back in stock','Official sale','New model launch'].map(t=>`<label class="checkbox-line"><input name="types" type="checkbox" value="${t}" ${types.includes(t)?'checked':''}> ${t}</label>`).join('')}</fieldset><p class="notice">Saved locally. Only price targets are checked against sample catalog prices while the app is open. Other choices are demo preferences; no live monitoring, email or push notifications run.</p><button class="button primary">Save target ↗</button></form></div>`);
  }
  function article(id) {const n=newsItems().find(x=>x.id===id);if(!n)return;modal={type:'article',id};showDialog(`<article class="article-dialog"><span class="eyebrow">${e(n.category)} · DEMO EDITORIAL</span><h1 id="detail-title">${e(n.title)}</h1><p class="muted">${e(n.date)} · ${n.read} min read · GadgetPulse original demo</p><div class="article-art">${V.art(n.art,n.color)}</div><p class="article-intro">${e(n.summary)}</p><p>${e(n.body)}</p><div class="notice">Original sample editorial content. This is not a live report or confirmed product announcement.</div><a href="#news" class="button secondary">Back to the feed ↗</a></article>`);}
  document.addEventListener('click',async event=>{
    const anchor=event.target.closest('a[href^="#"]');
    if(anchor?.getAttribute('href')==='#content'){event.preventDefault();$('#content').focus({preventScroll:true});$('#content').scrollIntoView({block:'start'});return;}
    if(anchor&&$('#detail-dialog').open)closeDialog();
    const button=event.target.closest('[data-action]');if(!button)return;
    const {action,id,query}=button.dataset;
    if(action==='close-dialog')closeDialog();
    else if(action==='detail'||action==='detail-reviews')openProduct(id,action==='detail-reviews'?'reviews':'specs');
    else if(action==='detail-tab')openProduct(modal.id,button.dataset.tab,false);
    else if(action==='article')article(id);
    else if(action==='track')track(id);
    else if(action==='quick-search')goto('explore',{q:query});
    else if(action==='search-focus'){goto('explore');setTimeout(()=>$('#search-form input')?.focus(),50);}
    else if(action==='wish'){state.wishlist=state.wishlist.includes(id)?state.wishlist.filter(x=>x!==id):[...state.wishlist,id];notifySaved(state.wishlist.includes(id)?'Saved to your wishlist.':'Removed from your wishlist.');refresh();}
    else if(action==='compare'){if(!state.comparisons.includes(id)&&state.comparisons.length===4){toast('Compare up to four devices. Remove one to add another.');return;}state.comparisons=C.toggleComparison(state.comparisons,id);notifySaved(state.comparisons.includes(id)?'Added to comparison.':'Removed from comparison.');refresh();}
    else if(action==='clear-compare'){state.comparisons=[];notifySaved('Comparison cleared.');refresh();}
    else if(action==='save-search'){state.searches=[query,...state.searches.filter(x=>x!==query)].slice(0,20);notifySaved('Search saved to your profile.');}
    else if(action==='delete-search'){state.searches=state.searches.filter(x=>x!==query);notifySaved('Saved search removed.');refresh();}
    else if(action==='remove-alert'){state.alerts=state.alerts.filter(a=>a.productId!==id);notifySaved('Price target removed.');refresh();}
    else if(action==='dismiss-onboarding'){state.onboarded=true;save();render();}
    else if(action==='delete-review'){const review=state.reviews.find(r=>r.id===id);state.reviews=state.reviews.filter(r=>r.id!==id);notifySaved('Local review deleted.');refresh();if(review)window.GadgetPulseMedia.remove(review.media).catch(()=>{});}
    else if(action==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='gadgetpulse-saved-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Saved profile exported. Media attachments remain in this browser.');}
    else if(action==='reset'&&window.confirm('Reset this browser profile, including wishlists, reviews, targets and demo edits?')){profileGeneration++;const keys=state.reviews.flatMap(r=>r.media);state=C.normalizeState(null,D.products.map(p=>p.id));notifySaved('Local profile reset.');refresh();window.GadgetPulseMedia.remove(keys).catch(()=>{});}
  });
  document.addEventListener('change',event=>{if(event.target.id==='city'){const city=D.cities[event.target.value];$('#state').value=city.state;$('#pin').value=city.pin;}});
  document.addEventListener('keydown',event=>{
    if(event.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!$('#detail-dialog').open){event.preventDefault();goto('explore');setTimeout(()=>$('#search-form input')?.focus(),50);}
    if(event.target.matches('[role="tab"]')&&['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const tabs=Array.from(document.querySelectorAll('.detail-tabs [role="tab"]'));let index=tabs.indexOf(event.target);index=event.key==='Home'?0:event.key==='End'?tabs.length-1:(index+(event.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;const tab=tabs[index].dataset.tab;openProduct(modal.id,tab,false);$(`#tab-${tab}`)?.focus();}
  });
  document.addEventListener('submit',async event=>{
    const form=event.target;if(!(form instanceof HTMLFormElement))return;event.preventDefault();const data=new FormData(form),all=products();
    if(form.id==='search-form'){const q=String(data.get('query')).trim();goto('explore',q?{q}:{});}
    else if(form.id==='filter-form'){const params=Object.fromEntries(data);params.q=route().params.get('q')||'';Object.keys(params).forEach(k=>{if(!params[k]||params[k]==='All')delete params[k];});goto(route().path,params);}
    else if(form.id==='finder-form'||form.id==='nearby-form')goto(form.id==='finder-form'?'finder':'nearby',Object.fromEntries(data));
    else if(form.id==='news-filter')goto('news',{q:data.get('q'),topic:data.get('topic'),...(data.has('followed')?{followed:'1'}:{})});
    else if(form.id==='preferences-form'){const budget=Number(data.get('budget'));if(!C.validTarget(budget)){toast('Enter a valid budget greater than zero.');return;}state.name=String(data.get('name')).trim()||'Gadget explorer';state.preferences={categories:data.getAll('categories'),brands:data.getAll('brands'),budget,priority:data.get('priority'),useCases:data.getAll('useCases'),notifications:data.has('notifications')};state.onboarded=true;notifySaved('Preferences saved. Your feed is now personalized.');goto('home');}
    else if(form.id==='track-form'){const target=Number(data.get('target'));if(!C.validTarget(target)){toast('Enter a positive target price.');return;}state.alerts=[{productId:form.dataset.id,target,types:data.getAll('types')},...state.alerts.filter(a=>a.productId!==form.dataset.id)];notifySaved('Price target saved on this browser.');closeDialog();render();}
    else if(form.id==='review-form'){
      const submit=form.querySelector('button[type="submit"],button:not([type])');submit.disabled=true;$('#review-error').textContent='';
      let keys=[];const submittedGeneration=profileGeneration;
      try{const review={id:`r-${Date.now()}-${Math.random().toString(36).slice(2)}`,productId:form.dataset.id,rating:Number(data.get('rating')),text:String(data.get('text')).trim(),date:new Date().toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}),breakdown:Object.fromEntries(['Performance','Camera','Battery','Display','Build','Software','Value'].map(k=>[k,Number(data.get(k))])),media:[]};if(!C.validReview(review))throw new Error('Choose a rating and write at least five characters.');keys=await window.GadgetPulseMedia.save(form.querySelector('[name="media"]').files);if(submittedGeneration!==profileGeneration)throw new Error('Review cancelled because the local profile was reset.');review.media=keys;state.reviews=[review,...state.reviews].slice(0,200);notifySaved('Review saved locally.');if(form.isConnected&&modal?.type==='product'&&modal.id===review.productId&&modal.tab==='reviews')openProduct(review.productId,'reviews',false);else render();}
      catch(error){if(form.isConnected){$('#review-error').textContent=error.message;submit.disabled=false;}else toast(error.message);if(keys.length)window.GadgetPulseMedia.remove(keys).catch(()=>{});}
    }
    else if(form.classList.contains('admin-form')){const price=Number(data.get('price'));if(!C.validTarget(price)){toast('Enter a valid positive demo price.');return;}state.overrides[form.dataset.id]={price,featured:data.has('featured'),reviewed:data.has('reviewed')};notifySaved('Demo catalog updated on this browser.');render();}
    else if(form.classList.contains('news-admin-form')){state.newsOverrides[form.dataset.id]={title:String(data.get('title')).trim(),summary:String(data.get('summary')).trim()};notifySaved('Demo article updated on this browser.');}
  });
  $('#detail-dialog').addEventListener('close',()=>{modal=null;releaseMedia();});
  $('#detail-dialog').addEventListener('click',event=>{if(event.target===$('#detail-dialog')){const rect=event.target.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)closeDialog();}});
  window.addEventListener('hashchange',()=>{closeDialog();render();window.scrollTo({top:0,behavior:'instant'});$('#content').focus({preventScroll:true});});
  render();
  try {localStorage.setItem('gadgetpulse-storage-check','1');localStorage.removeItem('gadgetpulse-storage-check');}catch(_){storageAvailable=false;toast('Browser storage is unavailable. You can explore, but saved changes last only for this session.');}
})();
