/* Wanderly data. Daily costs (per person, ₹) are ILLUSTRATIVE ranges: edit them for current prices. */
const DEST=[
 {id:"goa",name:"Goa",country:"India",e:"🏖️",type:"beach",best:"Nov–Feb",cost:{budget:2500,mid:5500,luxury:13000},
  acts:{relax:["Sunrise on Palolem beach","Sunset at Vagator","Spa morning in Candolim"],food:["Fish thali at a Goan shack","Bebinca and cafés in Panjim","Feni and seafood in Anjuna"],adventure:["Parasailing at Calangute","Scuba at Grande Island","Kayaking in Chapora"],culture:["Old Goa churches (Basilica of Bom Jesus)","Fontainhas Latin Quarter walk","Fort Aguada"],nature:["Dudhsagar Falls trip","Mangrove boat ride","Cotigao Wildlife Sanctuary"]}},
 {id:"jaipur",name:"Jaipur",country:"India",e:"🏰",type:"city",best:"Oct–Mar",cost:{budget:2200,mid:5000,luxury:14000},
  acts:{relax:["Chokhi Dhani village evening","Rooftop tea with a fort view","Garden walk at Sisodia Rani Bagh"],food:["Dal baati churma lunch","Lassi at Lassiwala","Street kachori in Johari Bazaar"],adventure:["Hot-air balloon over Amer","Jeep ride near Nahargarh","Cycling tour of the old city"],culture:["Amer Fort","City Palace and Jantar Mantar","Hawa Mahal and bazaars"],nature:["Sunrise at Nahargarh","Jal Mahal lakeside walk","Galtaji monkey temple hike"]}},
 {id:"manali",name:"Manali",country:"India",e:"🏔️",type:"mountain",best:"Mar–Jun, Dec–Feb",cost:{budget:2000,mid:4800,luxury:11000},
  acts:{relax:["Hot springs at Vashisht","Riverside café on Mall Road","Apple orchard picnic"],food:["Siddu and trout fish","Tibetan momos in Old Manali","Café hopping in Old Manali"],adventure:["Paragliding in Solang Valley","River rafting on the Beas","Rohtang / Atal Tunnel day trip"],culture:["Hadimba Temple","Manu Temple","Naggar Castle"],nature:["Jogini Falls trek","Solang Valley","Beas Kund trek"]}},
 {id:"kerala",name:"Kerala",country:"India",e:"🛶",type:"beach",best:"Oct–Mar",cost:{budget:2400,mid:5500,luxury:15000},
  acts:{relax:["Houseboat in Alleppey backwaters","Ayurvedic massage in Kovalam","Varkala cliff sunset"],food:["Sadya on a banana leaf","Appam and stew breakfast","Fort Kochi seafood"],adventure:["Kayaking in Kumarakom","Trek in Munnar hills","Bamboo rafting in Thekkady"],culture:["Kathakali show in Kochi","Chinese fishing nets, Fort Kochi","Padmanabhaswamy Temple"],nature:["Munnar tea plantations","Periyar boat safari","Athirappilly Falls"]}},
 {id:"tokyo",name:"Tokyo",country:"Japan",e:"🗼",type:"city",best:"Mar–May, Oct–Nov",cost:{budget:7000,mid:15000,luxury:35000},
  acts:{relax:["Onsen day trip","Shinjuku Gyoen garden","Tea at a Ginza café"],food:["Sushi at Tsukiji Outer Market","Ramen alley in Shinjuku","Izakaya night in Shibuya"],adventure:["Day trip to Mt. Fuji","Go-kart through Tokyo","Cycling in Odaiba"],culture:["Senso-ji Temple","Meiji Shrine","TeamLab digital art museum"],nature:["Cherry blossoms at Ueno Park","Hakone lake cruise","Mt. Takao hike"]}},
 {id:"bali",name:"Bali",country:"Indonesia",e:"🌴",type:"beach",best:"Apr–Oct",cost:{budget:4000,mid:9000,luxury:22000},
  acts:{relax:["Beach club in Seminyak","Yoga in Ubud","Uluwatu sunset"],food:["Warung nasi campur","Babi guling in Ubud","Cooking class with a market trip"],adventure:["Surf lesson in Canggu","Sunrise trek on Mt. Batur","Snorkel at Nusa Penida"],culture:["Uluwatu Temple Kecak dance","Tirta Empul water temple","Ubud art markets"],nature:["Tegallalang rice terraces","Sekumpul Waterfall","Sacred Monkey Forest"]}}
];
const PHRASES={
 ja:{name:"Japanese",lang:"ja-JP",list:[["Hello","こんにちは","Konnichiwa"],["Thank you","ありがとうございます","Arigatou gozaimasu"],["Please","お願いします","Onegaishimasu"],["How much is this?","いくらですか","Ikura desu ka?"],["Where is the toilet?","トイレはどこですか","Toire wa doko desu ka?"],["It's delicious","おいしい","Oishii"],["Excuse me / Sorry","すみません","Sumimasen"],["Help!","助けて","Tasukete!"]]},
 id:{name:"Indonesian (Bali)",lang:"id-ID",list:[["Hello","Halo","Halo"],["Thank you","Terima kasih","Teri-ma ka-seh"],["Please","Tolong","Tolong"],["How much is this?","Berapa harganya?","Be-ra-pa har-ga-nya?"],["Where is the toilet?","Di mana toilet?","Dee ma-na toilet?"],["It's delicious","Enak","E-nak"],["Excuse me","Permisi","Per-mee-see"],["Help!","Tolong!","Tolong!"]]},
 hi:{name:"Hindi",lang:"hi-IN",list:[["Hello","नमस्ते","Namaste"],["Thank you","धन्यवाद","Dhanyavaad"],["Please","कृपया","Kripya"],["How much is this?","यह कितने का है?","Yah kitne ka hai?"],["Where is the toilet?","शौचालय कहाँ है?","Shauchalay kahaan hai?"],["It's delicious","बहुत स्वादिष्ट","Bahut swadisht"],["Excuse me / Sorry","माफ़ कीजिए","Maaf kijiye"],["Help!","मदद कीजिए!","Madad kijiye!"]]},
 ml:{name:"Malayalam (Kerala)",lang:"ml-IN",list:[["Hello","നമസ്കാരം","Namaskaram"],["Thank you","നന്ദി","Nanni"],["Please","ദയവായി","Dayavayi"],["How much is this?","ഇതിന് എത്രയാണ് വില?","Ithinu ethrayaanu vila?"],["Where is the toilet?","ശൗചാലയം എവിടെയാണ്?","Shauchalayam evideyaanu?"],["It's delicious","വളരെ രുചികരം","Valare ruchikaram"],["Excuse me / Sorry","ക്ഷമിക്കണം","Kshamikkanam"],["Help!","സഹായിക്കൂ!","Sahayikku!"]]}
};
/* Approximate fallback rates: 1 INR = x. Live rates replace these when online. */
const RATES={USD:.012,EUR:.011,GBP:.0095,JPY:1.8,IDR:190,AED:.044,THB:.4,SGD:.016,INR:1};
const PACK={
 base:[["Documents",["Passport / ID","Tickets & bookings","Travel insurance copy","Some cash"]],["Tech",["Phone & charger","Power bank","Universal adapter","Headphones"]],["Toiletries",["Toothbrush & paste","Sunscreen","Personal medicines","Hand sanitiser"]]],
 beach:["Swimwear","Flip-flops","Sunglasses","Beach towel","Light cotton clothes"],mountain:["Warm jacket","Trekking shoes","Thermal innerwear","Gloves & cap","Lip balm"],
 city:["Comfortable walking shoes","Day backpack","Light jacket","Reusable water bottle"],cold:["Heavy coat","Thermals","Woollen socks","Moisturiser"],
 hiking:["Daypack","First-aid kit","Trail snacks","Rain poncho"],swim:["Quick-dry towel","Waterproof phone pouch"],work:["Laptop","Notebook & pen"]
};
